# Generated by Django 5.0.7 on 2024-07-30 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_info_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_10',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_11',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_12',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_13',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_14',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_15',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_16',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_6',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_7',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_9',
        ),
        migrations.AlterField(
            model_name='info_module',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_module', to='shop.info'),
        ),
    ]
