# Generated by Django 5.0.7 on 2024-07-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_image_image_1_remove_image_image_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_module',
            name='image',
            field=models.ImageField(blank=True, upload_to='info/%Y/%m/%d'),
        ),
    ]
