# Generated by Django 5.0.7 on 2024-07-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_unit_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(blank=True, choices=[("so'm", 'Uz'), ('rubl', 'Ru'), ('dollar', 'Amr')], default="so'm", max_length=10, null=True),
        ),
    ]
