# Generated by Django 5.0.7 on 2024-07-30 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_info_module_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
