# Generated by Django 5.0.7 on 2024-07-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_module',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='info/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='info_module',
            name='image_10',
            field=models.ImageField(blank=True, upload_to='info/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='info_module',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='info/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='info_module',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='info/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='info_module',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='info/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='info_module',
            name='image_5',
            field=models.ImageField(blank=True, upload_to='info/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='info_module',
            name='image_6',
            field=models.ImageField(blank=True, upload_to='info/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='info_module',
            name='image_7',
            field=models.ImageField(blank=True, upload_to='info/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='info_module',
            name='image_9',
            field=models.ImageField(blank=True, upload_to='info/%Y/%m/%d'),
        ),
    ]
